//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyStarcraft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxyStarcraft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;buffId&quot;: 1, &quot;name&quot;: &quot;Radar25&quot; }	
        ///{ &quot;buffId&quot;: 2, &quot;name&quot;: &quot;tauntb&quot; }	
        ///{ &quot;buffId&quot;: 3, &quot;name&quot;: &quot;DisableAbils&quot; }	
        ///{ &quot;buffId&quot;: 4, &quot;name&quot;: &quot;TransientMorph&quot; }	
        ///{ &quot;buffId&quot;: 5, &quot;name&quot;: &quot;GravitonBeam&quot; }	
        ///{ &quot;buffId&quot;: 6, &quot;name&quot;: &quot;GhostCloak&quot; }	
        ///{ &quot;buffId&quot;: 7, &quot;name&quot;: &quot;BansheeCloak&quot; }	
        ///{ &quot;buffId&quot;: 8, &quot;name&quot;: &quot;PowerUserWarpable&quot; }	
        ///{ &quot;buffId&quot;: 9, &quot;name&quot;: &quot;VortexBehaviorEnemy&quot; }	
        ///{ &quot;buffId&quot;: 10, &quot;name&quot;: &quot;Corruption&quot; }	
        ///{ &quot;buffId&quot;: 11, &quot;name&quot;: &quot;QueenSpawnLarvaTimer&quot; }	
        ///{ &quot;buffId&quot;: 12, &quot;name&quot;: &quot;GhostHoldFire&quot; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buff_Name_List {
            get {
                return ResourceManager.GetString("Buff_Name_List", resourceCulture);
            }
        }
    }
}
