namespace ProxyStarcraft
{
    public enum TerranBuildingType
    {
        CommandCenter,
        Refinery,
        SupplyDepot,
        Barracks,
        EngineeringBay,
        Bunker,
        SensorTower,
        MissileTurret,
        Factory,
        GhostAcademy,
        Starport,
        Armory,
        FusionCore,
        TechLab,
        Reactor,
        BarracksTechLab,
        BarracksReactor,
        FactoryTechLab,
        FactoryReactor,
        StarportTechLab,
        StarportReactor,
        PlanetaryFortress,
        OrbitalCommand
    }
}
